name: Release

on:
  workflow_dispatch:
    inputs:
      draft:
        description: Make Draft
        default: false
        required: true
        type: boolean
      version:
        description: "Version ([+]X.Y.Z)"
        required: false
        type: string
  workflow_call:
    inputs:
      draft:
        description: Whether to make this a draft release, or a finished release.
        default: false
        required: true
        type: boolean
      sha:
        description: "The commit to check out at. Defaults to the parent workflow's github.sha."
        required: false
        type: string
      version:
        description: The version to release as. If it starts with a plus, it is relative to the previous release.
        required: true
        type: string
    outputs:
      sha:
        description: The resulting SHA commitish.
        value: ${{ jobs.release.outputs.sha }}

jobs:
  test:
    name: Test
    uses: ./.github/workflows/test.yml
    with:
      sha: ${{ inputs.sha }}

  leakcheck:
    name: Test (leakcheck)
    uses: ./.github/workflows/leakcheck.yml
    with:
      sha: ${{ inputs.sha }}

  release:
    name: Release
    needs: [test, leakcheck]
    runs-on: ubuntu-latest
    outputs:
      committed: ${{ steps.commit_changelog.outputs.committed }}
      sha: ${{ steps.commit_changelog.outputs.commit_long_sha }}
    steps:
    - name: Checkout
      uses: actions/checkout@v4
      with:
        fetch-depth: 1
        ref: ${{ inputs.sha }}

    - name: Mark Release In Changelog
      if: ${{ inputs.version }}
      run: |
        ./tools/modifychangelog.py --release "${{ inputs.version }}" --inplace CHANGELOG.md

    - name: Get Changelog Information
      id: changelog
      run: |
        set -o pipefail

        version=$(sed -e 's;^##\s\+\[\(v[0-9.]\+\)\].*;\1; p ; d' CHANGELOG.md | head -n 1)

        (
          echo "Full changelog ⇒ [$version](https://github.com/${{ github.repository }}/blob/$version/CHANGELOG.md)"

          awk -v version="$version" '
            /^##\s+\[.*?\]\s/ && $2 != "[" version "]" {
              inside = 0;
            }
            inside && (inside == 2 || $0) {
              gsub(/^#/, "");
              print;
              if ($0) { inside = 2; }
            }
            /^##\s+\[.*?\]\s/ && $2 == "[" version "]" {
             inside = 1;
            }' CHANGELOG.md | \
            sed -Ez '$ s/\n+$/\n/'
        ) >releasenotes.md

        echo "version=$version" >>"$GITHUB_OUTPUT"

    - id: commit_changelog
      name: Commit
      if: ${{ inputs.version }}
      uses: EndBug/add-and-commit@v9
      with:
        add: CHANGELOG.md
        fetch: false
        push: origin HEAD:${{ github.ref_name }}
        message: |
          Update changelog to ${{ steps.changelog.outputs.version }}

          Auto-generated by GitHub workflow release.

    - id: find_commit
      name: Determine Commit To Release
      run: |
        changelog='${{ steps.commit_changelog.outputs.commit_long_sha }}'
        original='${{ github.sha }}'

        # When using push: origin HEAD:x, the status output looks like "HEAD x".
        commit_sha="${changelog:-$original}"
        commit_sha="${commit_sha#HEAD }"

        echo "commit=$commit_sha" >>"$GITHUB_OUTPUT"

    - id: create_release
      name: Create Release
      uses: ncipollo/release-action@v1
      with:
        commit: ${{ steps.find_commit.outputs.commit }}
        tag: ${{ steps.changelog.outputs.version }}
        bodyFile: releasenotes.md
        draft: ${{ inputs.draft }}
        allowUpdates: true
        updateOnlyUnreleased: true

    - name: Create Summary
      run: |
        echo "Tag: ${{ steps.changelog.outputs.version }}" >>"$GITHUB_STEP_SUMMARY"
        echo "Commit: https://github.com/the-btfash-foundation/v8go/commit/${{ steps.find_commit.outputs.commit }}" >>"$GITHUB_STEP_SUMMARY"
        echo "Release: ${{ steps.create_release.outputs.html_url }}" >>"$GITHUB_STEP_SUMMARY"
